package com.google.android.gms.internal.cast;

/* loaded from: /Users/liqi/android-frida-traces/apk_test/dex_files/classes.dex */
public enum zzml {
    DEVELOPER_FEATURE_FLAG_UNKNOWN(0),
    CAF_CAST_BUTTON(1),
    CAF_EXPANDED_CONTROLLER(2),
    CAF_MINI_CONTROLLER(3),
    CAF_CONTAINER_CONTROLLER(4),
    CAST_CONTEXT(5),
    IMAGE_CACHE(6),
    IMAGE_PICKER(7),
    AD_BREAK_PARSER(8),
    UI_STYLE(9),
    HARDWARE_VOLUME_BUTTON(10),
    NON_CAST_DEVICE_PROVIDER(11),
    PAUSE_CONTROLLER(12),
    SEEK_CONTROLLER(13),
    STREAM_VOLUME(14),
    UI_MEDIA_CONTROLLER(15),
    PLAYBACK_RATE_CONTROLLER(16),
    PRECACHE(17),
    INSTRUCTIONS_VIEW(18),
    OPTION_SUSPEND_SESSIONS_WHEN_BACKGROUNDED(19),
    OPTION_STOP_RECEIVER_APPLICATION_WHEN_ENDING_SESSION(20),
    OPTION_DISABLE_DISCOVERY_AUTOSTART(21),
    OPTION_DISABLE_ANALYTICS_LOGGING(22),
    OPTION_PHYSICAL_VOLUME_BUTTONS_WILL_CONTROL_DEVICE_VOLUME(23),
    CAF_EXPANDED_CONTROLLER_HIDE_STREAM_POSITION_CONTROLS_FOR_LIVE_CONTENT(24),
    CAF_EXPANDED_CONTROLLER_WITH_LIVE_CONTENT(25),
    REMOTE_MEDIA_CLIENT_LOAD_MEDIA_WITH_OPTIONS(26),
    REMOTE_MEDIA_CLIENT_QUEUE_LOAD_ITEMS_WITH_OPTIONS(27),
    REMOTE_MEDIA_CLIENT_LOAD_MEDIA_WITH_LOAD_REQUEST_DATA(28),
    LAUNCH_OPTION_ANDROID_RECEIVER_COMPATIBLE(29),
    CAST_CONTEXT_SET_LAUNCH_CREDENTIALS_DATA(30),
    START_DISCOVERY_AFTER_FIRST_TAP_ON_CAST_BUTTON(31),
    CAST_UNAVAILABLE_BUTTON_VISIBLE(32),
    CAST_DEFAULT_MEDIA_ROUTER_DIALOG(33),
    CAST_CUSTOM_MEDIA_ROUTER_DIALOG(34),
    CAST_OUTPUT_SWITCHER_ENABLED(35),
    CAST_TRANSFER_TO_LOCAL_ENABLED(36),
    CAST_BUTTON_IS_TRIGGERED_DEFAULT_CAST_DIALOG_FALSE(37),
    CAST_BUTTON_DELEGATE(38),
    CAST_BUTTON_DELEGATE_PRESENT_LNA_PERMISSION_CUSTOM_DIALOG(39),
    CAST_BUTTON_DELEGATE_PRESENT_CAST_STATE_CUSTOM_DIALOG(40),
    CAST_TRANSFER_TO_LOCAL_USED(41),
    MEDIA_REQUEST_ITEM_MAP_HLS_SEGMENT_FORMAT_TO_STRING(42),
    MEDIA_REQUEST_ITEM_MAP_HLS_SEGMENT_FORMAT_STRING_TO_ENUM(43),
    HLS_SEGMENT_MAP_HLS_SEGMENT_FORMAT_TO_STRING(44),
    HLS_SEGMENT_MAP_HLS_SEGMENT_FORMAT_STRING_TO_ENUM(45),
    HLS_VIDEO_SEGMENT_MAP_HLS_VIDEO_SEGMENT_FORMAT_TO_STRING(46),
    HLS_VIDEO_SEGMENT_MAP_HLS_VIDEO_SEGMENT_FORMAT_STRING_TO_ENUM(47),
    CAST_SLIDER_SET_AD_BLOCK_POSITIONS(48),
    CAF_NOTIFICATION_SERVICE(49),
    HARDWARE_VOLUME_BUTTON_PRESS(50),
    CAST_SDK_DEFAULT_DEVICE_DIALOG(51),
    CAST_SDK_CUSTOM_DEVICE_DIALOG(52),
    PERSISTENT_CAST_BUTTON_DISCOVERY_DISABLED_WITH_CONFLICT_TYPES(53),
    CAST_DEVICE_DIALOG_FACTORY_INSTANTIATED(54),
    CAF_MEDIA_NOTIFICATION_PROXY(55);

    private static final zzts zzae = new zzts() { // from class: com.google.android.gms.internal.cast.zzmj
    };
    private final int zzag;

    zzml(int i) {
        this.zzag = i;
    }

    public static zztt zzb() {
        return zzmk.zza;
    }

    @Override // java.lang.Enum
    public final String toString() {
        return Integer.toString(this.zzag);
    }

    public final int zza() {
        return this.zzag;
    }
}
